### ISSUE TITLE
I've added you to the awesome-streamlit.org resources list. Hope its ok?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Poseyy/StreamlitDemo#1]
Hi Luke

I've added you to the [awesome-streamlit.org](https://awesome-streamlit.org) resources list. 

Hope it's ok?

Feel free to add your code example(s) to the gallery as code contributions to 
the [repo](https://github.com/marcskovmadsen/awesome-streamlit)

I might also do it later if I get the time. Hope that would be ok as well?

Marc

![image](https://user-images.githubusercontent.com/42288570/67260809-c1348c00-f49d-11e9-9155-a31858cdafb9.png)

**Comment by Poseyy** [comment]
Totally cool, thanks Marc. I'm currently cleaning this repo up considerably.
